### ISSUE TITLE
Signatures not correct on integrated platform

### ISSUE THREAD

**Issue by nikibrown** [nikibrown/bloc-grading-chrome-extension#8]
Hey @obedparla 

So I think we need a few more controls in the options page. 

These lines of code here are what I think is causing the issue:

https://github.com/nikibrown/bloc-grading-chrome-extension/blob/master/grading-msg.js#L22

`isBloc` and `isThinkful` logic does not work for the integrated platform programs. We have WDT, SDT, SET, and DT on the legacy Bloc platform (bloc.io domain), but we also have WDT and DT on the integrated platform. 

The URL's for these assignments are located at lark.thinkful.com so theres no unique thing in the URL that identifies them as Bloc branded. For example https://lark.thinkful.com/grading/contacts/t:469776/assignments/2342/ This is a DT students assignment. 

To solve this problem I think we need another toggle button on the options page to identify if someone is doing Thinkful grading or Bloc grading. 

Let me know if that makes sense. 

Once this is fixed please test by claiming checkpoints from the legacy bloc platform for both dev and design, and on the integrated platform for dev and design, and then thinkful FSF (dev) and PDF (design). Obviously, don't grade but just see if the text auto-populates the textarea. 

Thanks, 

N

**Comment by obedparla** [comment]
Hey @nikibrown, 

I got confused while working on this. I understand we have some of the same programs on both bloc and the integrated platform, but how does a grader know the difference? 

Personally, when I grade, I know whether I'm grading Bloc or Thinkful based on the URL. 

The way I understood you, even if you're on `lark.thinkful.com`, you might be grading a Bloc student. Is that correct? If so, how can a grader know she's grading Bloc or Thinkful and select the option in the extension accordingly? 

I'd much rather find a way to automate it. I feel it would be painful to have to change the extension's settings for every submission, and prone to people making mistakes since we can grade many programs from both Bloc / Thinkful at the same time 🤔

**Comment by nikibrown** [comment]
Hi @obedparla 

So graders will know which platform they are grading on because the most likely will just select 1 program from the filter. We have the WDT and DT bloc programs that are hosted on the integrated platform. So perhaps we do just need toggles for bloc/thinkful. I sent you a slack message but can you grab a spot on my schedule of that works for you? https://calendly.com/nikibrown/



Thanks for all your help with this!

**Comment by nikibrown** [comment]
Hi @obedparla  So I think UX wise I have a simpler way to go about this. We just need buttons that allow the grader to select the specific program they are grading for. 

Design track, product design flex, web development track, software development track, full stack flex, Engineering immersion, data analytics, data science

I have a gist with all the signatures here:

https://gist.github.com/nikibrown/296ffb9ef8547c89585718376af8c10d

We should still have them add their name and maybe customize the greeting at the top (although if its easier we can just remove it and have the same greeting). 

Can you get a test branch of this done today or tomorrow?

Thanks

N

**Comment by obedparla** [comment]
Hey @nikibrown, 

Update done on https://github.com/nikibrown/bloc-grading-chrome-extension/pull/9

I tested on all the programs listed and fixed the issues you mentioned in the PR. Do let me know if you have that issue with the text not being populated as I can't reproduce it.
